/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "auth": {                                        "en": "Authentication Details",                          "de": "Authentifizierung Details",                       "ru": "Подробности Проверки Подлинности ",               "pt": "Detalhes De Autenticação",                        "nl": "Verificatie Details",                             "fr": "Les Informations D'Authentification",             "it": "Dettagli Di Autenticazione",                      "es": "Los Detalles De Autenticación",                   "pl": "Szczegóły Uwierzytelniania ",                     "zh-cn": "身份验证的细节"},
    "delay": {                                       "en": "Delay",                                           "de": "Verzögerung",                                     "ru": "Задержка",                                        "pt": "Atraso",                                          "nl": "Vertraging",                                      "fr": "Retard",                                          "it": "Ritardo",                                         "es": "Retraso",                                         "pl": "Opóźnienie",                                      "zh-cn": "延迟"},
    "ip": {                                          "en": "IP address",                                      "de": "Die IP-Adresse",                                  "ru": "IP-адрес",                                        "pt": "Endereço IP",                                     "nl": "IP-adres",                                        "fr": "Adresse IP",                                      "it": "Indirizzo IP",                                    "es": "Dirección IP",                                    "pl": "Adres IP",                                        "zh-cn": "IP地址"},
    "port": {                                        "en": "Port",                                            "de": "Port",                                            "ru": "Порт",                                            "pt": "Porta",                                           "nl": "Poort",                                           "fr": "Port",                                            "it": "Porta",                                           "es": "Puerto",                                          "pl": "Port",                                            "zh-cn": "口"},
    "steps": {                                       "en": "Steps",                                           "de": "Schritte",                                        "ru": "Шаги",                                            "pt": "Passos",                                          "nl": "Stappen",                                         "fr": "Étapes",                                          "it": "Passi",                                           "es": "Pasos",                                           "pl": "Kroki",                                           "zh-cn": "步骤"},
};